import { describe, expect, it } from 'vitest';
import { extractPolicyLines as extractPolicy } from '../src/compiler/policy.js';

describe('extractPolicy', () => {
  it('extracts lines containing "must"', () => {
    const content = 'You must run this first.\nOptional step.\nYou must also check logs.';
    const result = extractPolicy(content);
    expect(result).toEqual([
      'You must run this first.',
      'You must also check logs.',
    ]);
  });

  it('extracts lines containing "never"', () => {
    const content = 'Never call this directly.\nSome text.\nNever skip validation.';
    const result = extractPolicy(content);
    expect(result).toEqual([
      'Never call this directly.',
      'Never skip validation.',
    ]);
  });

  it('extracts lines containing "always"', () => {
    const content = 'Always validate input.\n# comment\nalways sanitize output.';
    const result = extractPolicy(content);
    expect(result).toEqual([
      'Always validate input.',
      'always sanitize output.',
    ]);
  });

  it('extracts lines containing "do not" (case insensitive)', () => {
    const content = 'Do not edit this file.\nDo NOT remove headers.\nSafe to modify.';
    const result = extractPolicy(content);
    expect(result).toEqual([
      'Do not edit this file.',
      'Do NOT remove headers.',
    ]);
  });

  it('extracts lines containing "required"', () => {
    const content = 'API key is required.\nOptional config.\nRequired: Node.js 18+.';
    const result = extractPolicy(content);
    expect(result).toEqual([
      'API key is required.',
      'Required: Node.js 18+.',
    ]);
  });

  it('extracts lines containing "security"', () => {
    const content = 'Security: never expose keys.\nThis is a security concern.\nNormal text.';
    const result = extractPolicy(content);
    expect(result).toEqual([
      'Security: never expose keys.',
      'This is a security concern.',
    ]);
  });

  it('finds multiple policy-relevant lines', () => {
    const content = [
      'You must authenticate first.',
      'Always use HTTPS.',
      'Never log credentials.',
      'Do not store plaintext passwords.',
      'This is a security requirement.',
      'Normal description here.',
    ].join('\n');
    const result = extractPolicy(content);
    expect(result).toEqual([
      'You must authenticate first.',
      'Always use HTTPS.',
      'Never log credentials.',
      'Do not store plaintext passwords.',
      'This is a security requirement.',
    ]);
  });

  it('returns empty array for content with no policy-relevant lines', () => {
    const content = 'This is a normal description.\nAnother normal line.\n# Heading';
    const result = extractPolicy(content);
    expect(result).toEqual([]);
  });

  it('returns empty array for empty content', () => {
    expect(extractPolicy('')).toEqual([]);
  });

  it('trims whitespace from matched lines', () => {
    const content = '  must trim this  \n  normal text  ';
    const result = extractPolicy(content);
    expect(result).toEqual(['must trim this']);
  });

  it('skips empty lines even if they would match (whitespace only)', () => {
    const content = 'must have content\n   \nrequired field';
    const result = extractPolicy(content);
    expect(result).toEqual(['must have content', 'required field']);
  });
});
